// Kelime-emoji eşleştirme tablosu
const emojiMap = {
    // Colors
    'Red': '🔴',
    'Blue': '🔵',
    'Green': '🟢',
    'Yellow': '🟡',
    'Purple': '🟣',
    'Pink': '🎀',
    'Orange': '🟠',
    'Brown': '🟤',
    'Black': '⚫',
    'White': '⚪',
    
    // Animals
    'Dog': '🐕',
    'Cat': '🐈',
    'Bird': '🐦',
    'Butterfly': '🦋',
    'Duck': '🦆',
    'Fish': '🐟',
    'Rabbit': '🐇',
    'Snake': '🐍',
    'Horse': '🐎',
    'Turtle': '🐢',
    'Monkey': '🐒',
    'Frog': '🐸',
    'Mouse': '🐁',
    'Chicken': '🐔',
    'Cow': '🐄',
    'Pig': '🐖',
    
    // Food & Drinks
    'Apple': '🍎',
    'Banana': '🍌',
    'Sandwich': '🥪',
    'Soup': '🍲',
    'Salad': '🥗',
    'Spaghetti': '🍝',
    'Pizza': '🍕',
    'Hamburger': '🍔',
    'Ice Cream': '🍦',
    'Water': '💧',
    'Milk': '🥛',
    'Egg': '🥚',
    'Cheese': '🧀',
    'Honey': '🍯',
    'Tea': '🍵',
    'Coffee': '☕',
    'Bread': '🍞',
    
    // Toys
    'Ball': '⚽',
    'Car': '🚗',
    'Train': '🚂',
    'Lego': '🧱',
    'Puzzle': '🧩',
    'Boat': '🚢',
    'Plane': '✈️',
    'Doll': '👶',
    'Robot': '🤖',
    'Kite': '🪁',
    'Present': '🎁',
    
    // Clothes
    'Shoes': '👞',
    'T-shirt': '👕',
    'Dress': '👗',
    'Skirt': '👗',
    'Pants': '👖',
    'Socks': '🧦',
    'Scarf': '🧣',
    'Gloves': '🧤',
    'Sweater': '👚',
    'Umbrella': '☂️',
    'Raincoat': '🧥',
    'Rainboots': '👢',
    'Sunglasses': '🕶️',
    'Shorts': '🩳',
    'Coat': '👖',
    'Hat': '🧢',
    'Boots': '👢',
    'Slippers': '🩴',

    
    // Body Parts
    'Head': '👤',
    'Nose': '👃',
    'Mouth': '👄',
    'Ear': '👂',
    'Eye': '👁️',
    'Hand': '👋',
    'Leg': '🦵',
    'Foot': '🦶',
    'Tongue': '👅',
    'Arm': '💪',
    
    // Numbers
    'One': '1️⃣',
    'Two': '2️⃣',
    'Three': '3️⃣',
    'Four': '4️⃣',
    'Five': '5️⃣',
    'Six': '6️⃣',
    'Seven': '7️⃣',
    'Eight': '8️⃣',
    'Nine': '9️⃣',
    'Ten': '🔟',
    'Eleven': '11',
    'Twelve': '12',
    'Thirteen': '13',
    'Fourteen': '14',
    'Fifteen': '15',
    'Sixteen': '16',
    'Seventeen': '17',
    'Eighteen': '18',
    'Nineteen': '19',
    'Twenty': '20',
    
    // Family
    'Mother': '👩',
    'Mom': '👩',
    'Dad': '👨',
    'Father': '👨',
    'Sister': '👧',
    'Brother': '👦',
    'Baby': '👶',
    'Grandmother': '👵',
    'Grandfather': '👴',
    
    // Weather & Seasons
    'Sunny': '☀️',
    'Rainy': '🌧️',
    'Windy': '💨',
    'Cloudy': '☁️',
    'Rain': '🌧️',
    'Snowy': '🌨️',
    'Sun': '☀️',
    'Cloud': '☁️',
    'Spring': '🌸',
    'Summer': '🏊',
    'Fall': '🍂',
    'Winter': '🧥',
    'Cold': '❄️',
    'Hot': '🔥',
    'Buoyancy': '🚢',
    'Swim': '🏊',

    // Classroom Objects
    'Book': '📚',
    'Pencil': '✏️',
    'Ruler': '📏',
    'Notebook': '📓',
    'Backpack': '🎒',
    'Scissors': '✂️',
    'Glue': '🧴',
    'Sharpener': '✏️',
    'Eraser': '✏️',
    'Window': '🪟',
    'Door': '🚪',
    'Crayon': '🖍️',
    'Schoolbag': '🎒',
    
    // Feelings & Emotions
    'Happy': '😀',
    'Sad': '😢',
    'Angry': '😠',
    'Hungry': '😋',
    'Thirsty': '🥤',
    'Scared': '😱',
    'Tired': '😴',
    'Surprised': '😮',
    'Sleepy': '😴',
    
    // Shapes
    'Circle': '⭕',
    'Triangle': '🔺',
    'Square': '⬛',
    'Heart': '💖',
    'Star': '⭐',
    'Rectangle': '▬',
    
    // House & Furniture
    'House': '🏠',
    'Chair': '🪑',
    'Table': '🗄️',
    'Bed': '🛏️',
    'Sofa': '🛋️',
    'Kitchen': '🍳',
    'Bathroom': '🚿',
    'Living Room': '🛋️',
    'Bedroom': '🛏️',
    'Fridge': '❄️',
    'Television': '📺',
    
    // Playground
    'Slide': '🛝',
    'Swing': '🔄',
    'See-saw': '⚖️',
    'Map': '🗺️',
    'Ferris wheel': '🎡',
    'Sandbox': '🏖️',
    'Bottle': '💧',
    
    // Days
    'Monday': '📅',
    'Tuesday': '📅',
    'Wednesday': '📅',
    'Thursday': '📅',
    'Friday': '📅',
    'Saturday': '📅',
    'Sunday': '📅',
    
    // Daily Actions
    'Eat': '🍽️',
    'Sleep': '💤',
    'Run': '🏃',
    'Walk': '🚶',
    'Jump': '⬆️',
    'Dance': '💃',
    'Swim': '🏊',
    'Draw': '🖌️',
    'Read': '📖',
    'Write': '✍️',
    'Count': '🔢',
    'Bounce': '⚾',
    'Row': '🚣',
    'Sing': '🎤',
    'Play': '🎮',
    'Tidy up': '🧹',
    'Dig': '⛏️',

    
    // Science
    'Fossil': '🦴',
    'Archeology': '🏺',
    'Magnetism': '🧲',
    'Volcano': '🌋',
    'Eruption': '💥',
    'Rainbow': '🌈',
    'Seed': '🌱',
    'Soil': '🌱',
    'Pickaxe': '⛏️',
    
    // Greetings & Basics
    'Hello': '👋',
    'Goodbye': '👋',
    'Yes': '✅',
    'No': '❌',
    'Stand up': '🧍',
    'Sit down': '🪑',
    'Open': '📖',
    'Close': '📕',
    'I like': '👍',
    'I don\'t like': '👎',
    'My school': '🏫',
    'My friends': '👧',
    'My teacher': '👩',
    
    // Polite Requests
    'Thank you': '🙏',
    'Please': '🙏',
    'You\'re welcome': '😊',
    'Here you are': '👐',
    'Excuse me': '🙋',
    
    // Classroom Rules
    'Listen': '👂',
    'Be quiet': '🤫',
    'Raise your hand': '🙋',
    'Share': '🤝',
    'Help': '🆘',
    'Be kind': '❤️',
    'Wait': '⏰',
    'Take turns': '🔄',
    'Clean up': '🧹',
    'Don\'t run': '🏃',
    'Turn off/on': '💡',
    'Look at': '👀',
};

// Kelime-emoji eşleştirme fonksiyonu
function getEmojiForWord(word) {
    // Eşleştirme tablosunda kelime varsa emojiyi döndür, yoksa boş string döndür
    return emojiMap[word] || '';
}

// Dışa aktarma
module.exports = {
    emojiMap,
    getEmojiForWord
};
