const themes = {
    "Animals": [
        { word: "Horse", sentence: "Horses run fast.", pronunciation: "Horsız ran fast.", translation: "Atlar hızlı koşar.", color: "lightgray" },
        { word: "Rabbit", sentence: "Rabbits like carrots.", pronunciation: "Rabıts layk kerıts.", translation: "Tavşanlar havuç sever.", color: "peachpuff" },
        { word: "Fish", sentence: "A fish can swim.", pronunciation: "E fiş ken suim.", translation: "Balık yüzebilir.", color: "lightblue" },
        { word: "Butterfly", sentence: "The butterfly is colorful.", pronunciation: "Dı batırflay iz kalırful.", translation: "Kelebek renklidir.", color: "lightpink" },
        { word: "Cat", sentence: "A cat says meow!", pronunciation: "E ket sez miyav!", translation: "Kedi miyav der!", color: "lavender" },
        { word: "Dog", sentence: "Dog woofs/barks.", pronunciation: "Dog vufs/barks.", translation: "Köpek havlar.", color: "tan" },
        { word: "Turtle", sentence: "The turtle is slow.", pronunciation: "Dı tırtıl iz slow.", translation: "Kaplumbağa yavaştır.", color: "lightgreen" },
        { word: "Monkey", sentence: "The monkey climbs trees.", pronunciation: "Dı manki klayms triiz.", translation: "Maymun ağaçlara tırmanır.", color: "lightsalmon" },
        { word: "Bird", sentence: "A bird says tweet tweet.", pronunciation: "E bırd sez tuvit tuvit.", translation: "Kuş cik cik der.", color: "lightyellow" },
        { word: "Duck", sentence: "The duck can swim.", pronunciation: "Dı dak ken suim.", translation: "Ördek yüzebilir.", color: "lightcyan" },
        { word: "Frog", sentence: "It's a big frog.", pronunciation: "İts e big frog.", translation: "Bu büyük bir kurbağa.", color: "lightgreen" },
        { word: "Mouse", sentence: "I'm a mouse. Squeak!", pronunciation: "Aym e maus. Sıkuiik!", translation: "Ben bir fareyim. Vik Vik!", color: "lightgray" },
        { word: "Chicken", sentence: "Chicken lives in a farm.", pronunciation: "Çikın livz in e farm.", translation: "Tavuk çiftlikte yaşar.", color: "lightyellow" },
        { word: "Cow", sentence: "The cow gives milk.", pronunciation: "Dı kau givz milk.", translation: "İnek süt verir.", color: "white" },
        { word: "Pig", sentence: "Pigs like mud.", pronunciation: "Pigs layk mad.", translation: "Domuzlar çamuru sever.", color: "pink" }
    ],
    "Colors": [
        { word: "Green", sentence: "This/It is green.", pronunciation: "Dis/İt iz griin.", translation: "Bu yeşil.", color: "lightgreen" },
        { word: "Red", sentence: "The tomato is red.", pronunciation: "Dı tomeyto iz red.", translation: "Domates kırmızıdır.", color: "lightcoral" },
        { word: "Yellow", sentence: "The sun is yellow.", pronunciation: "Dı san iz yelov.", translation: "Güneş sarıdır.", color: "lightyellow" },
        { word: "Blue", sentence: "The sky is blue.", pronunciation: "Dı skay iz blu.", translation: "Gökyüzü mavidir.", color: "lightblue" },
        { word: "Black", sentence: "My shoes are black.", pronunciation: "May şuuz ar blek.", translation: "Ayakkabılarım siyah.", color: "lightgray" },
        { word: "Orange", sentence: "The orange is orange.", pronunciation: "Dı orinç iz orinç.", translation: "Portakal turuncudur.", color: "orange" },
        { word: "Pink", sentence: "This is a pink dress.", pronunciation: "Dis iz e pink dres.", translation: "Bu pembe bir elbise.", color: "lightpink" },
        { word: "Purple", sentence: "This is a purple crayon.", pronunciation: "Dis iz e pörpıl kreyon.", translation: "Bu mor bir pastel boya.", color: "plum" }
    ],
    "Food & Drinks": [
        { word: "Milk", sentence: "I want some milk.", pronunciation: "Ay vant sam milk.", translation: "Biraz süt istiyorum.", color: "white" },
        { word: "Bread", sentence: "I want some bread.", pronunciation: "Ay vant sam bred.", translation: "Biraz ekmek istiyorum.", color: "tan" },
        { word: "Cheese", sentence: "I like cheese.", pronunciation: "Ay layk çiiz.", translation: "Peyniri severim.", color: "lightyellow" },
        { word: "Egg", sentence: "I want an egg.", pronunciation: "Ay vant en eg.", translation: "Bir yumurta istiyorum.", color: "beige" },
        { word: "Honey", sentence: "I like honey.", pronunciation: "Ay layk hani.", translation: "Balı severim.", color: "gold" },
        { word: "Water", sentence: "I'm thirsty. I want some water.", pronunciation: "Aym törsti. Ay vant sam votör.", translation: "Susadım. Biraz su istiyorum.", color: "lightblue" },
        { word: "Apple", sentence: "I want an apple.", pronunciation: "Ay vant en epıl.", translation: "Bir elma istiyorum.", color: "lightcoral" },
        { word: "Banana", sentence: "I very like banana.", pronunciation: "Ay veri layk bınana.", translation: "Muzu çok severim.", color: "lightyellow" },
        { word: "Sandwich", sentence: "What do you want in your sandwich?", pronunciation: "Vat du yu vant in yor sendviç?", translation: "Sandviçine ne koymak istersin?", color: "wheat" },
        { word: "Soup", sentence: "Soup is boiling.", pronunciation: "Sup iz boyling.", translation: "Çorba kaynıyor.", color: "lightsalmon" },
        { word: "Salad", sentence: "Do you like salad?", pronunciation: "Du yu layk seled?", translation: "Salatayı sever misin?", color: "lightgreen" },
        { word: "Spaghetti", sentence: "I want spaghetti.", pronunciation: "Ay vant sıpagöti.", translation: "Spagetti istiyorum.", color: "lightyellow" }
    ],
    "Numbers": [
        { word: "One", sentence: "I have one ball.", pronunciation: "Ay hev van bol.", translation: "Bir topum var.", color: "lightblue" },
        { word: "Two", sentence: "I have two feet.", pronunciation: "Ay hev tu fiit.", translation: "İki ayağım var.", color: "lightpink" },
        { word: "Three", sentence: "How many legs does it have? Three legs.", pronunciation: "Hav meni legs daz it hev? Trii legs.", translation: "Kaç bacağı var? Üç bacak.", color: "lightyellow" },
        { word: "Four", sentence: "I have four crayons.", pronunciation: "Ay hev for kreyonz.", translation: "Dört pastel boyam var.", color: "lightgreen" },
        { word: "Five", sentence: "I want five apples.", pronunciation: "Ay vant fayv epılz.", translation: "Beş elma istiyorum.", color: "lightcyan" },
        { word: "Six", sentence: "Count to six.", pronunciation: "Kavnt tu siks.", translation: "Altıya kadar say.", color: "lavender" },
        { word: "Seven", sentence: "There are seven days in a week.", pronunciation: "Der ar sevın deyz in e viik.", translation: "Bir haftada yedi gün vardır.", color: "peachpuff" },
        { word: "Eight", sentence: "I have eight fingers.", pronunciation: "Ay hev eyt fingırz.", translation: "Sekiz parmağım var.", color: "lightcoral" },
        { word: "Nine", sentence: "Nine is after eight.", pronunciation: "Nayn iz aftır eyt.", translation: "Dokuz sekizden sonra gelir.", color: "lightsteelblue" },
        { word: "Ten", sentence: "I count to ten.", pronunciation: "Ay kavnt tu ten.", translation: "Ona kadar sayarım.", color: "plum" },
        { word: "Eleven", sentence: "Eleven is after ten.", pronunciation: "İlevın iz aftır ten.", translation: "Onbir ondan sonra gelir.", color: "lightcoral" },
        { word: "Twelve", sentence: "Twelve is after eleven.", pronunciation: "Tuelv iz aftır ilevın.", translation: "Oniki onbirden sonra gelir.", color: "lightsteelblue" },
        { word: "Thirteen", sentence: "Thirteen is after twelve.", pronunciation: "Törtiin iz aftır tuelv.", translation: "Onüç onikiden sonra gelir.", color: "plum" },
        { word: "Fourteen", sentence: "Fourteen is after thirteen.", pronunciation: "Fortiin iz aftır törtiin.", translation: "Ondört onüçden sonra gelir.", color: "lightcoral" },
        { word: "Fifteen", sentence: "Fifteen is after fourteen.", pronunciation: "Fiftiin iz aftır fortiin.", translation: "Onbeş ondörtten sonra gelir.", color: "lightsteelblue" },
        { word: "Sixteen", sentence: "Sixteen is after fifteen.", pronunciation: "Sikstiin iz aftır fiftiin.", translation: "Onaltı onbeşden sonra gelir.", color: "plum" },
        { word: "Seventeen", sentence: "Seventeen is after sixteen.", pronunciation: "Sevıntiin iz aftır sikstiin.", translation: "Onyedi onaltıdan sonra gelir.", color: "lightcoral" },
        { word: "Eighteen", sentence: "Eighteen is after seventeen.", pronunciation: "Eytiin iz aftır sevıntiin.", translation: "Onsekiz onyediden sonra gelir.", color: "lightsteelblue" },
        { word: "Nineteen", sentence: "Nineteen is after eighteen.", pronunciation: "Nayntiin iz aftır eytiin.", translation: "Onbirsekiz onsekizden sonra gelir.", color: "plum" },
        { word: "Twenty", sentence: "Twenty is after nineteen.", pronunciation: "Tuenti iz aftır nayntiin.", translation: "Onikinci onbirsekizden sonra gelir.", color: "lightcoral" }
    ],
    "Family": [
        { word: "Mom", sentence: "This is my mom.", pronunciation: "Dis iz may mam.", translation: "Bu benim annem.", color: "lightpink" },
        { word: "Dad", sentence: "My dad is tall.", pronunciation: "May ded iz tol.", translation: "Babam uzun boylu.", color: "lightblue" },
        { word: "Brother", sentence: "I have one brother.", pronunciation: "Ay hev van bradır.", translation: "Bir erkek kardeşim var.", color: "lightgreen" },
        { word: "Sister", sentence: "I have one sister.", pronunciation: "Ay hev van sistır.", translation: "Bir kız kardeşim var.", color: "lightyellow" },
        { word: "Baby", sentence: "This is my baby.", pronunciation: "Dis iz may beybi.", translation: "Bu benim bebeğim.", color: "lightcyan" },
        { word: "Family", sentence: "This is my family.", pronunciation: "Dis iz may femıli.", translation: "Bu benim ailem.", color: "lavender" }
    ],
    "Toys": [
        { word: "Boat", sentence: "I'm playing with my boat.", pronunciation: "Aym pleying vit may bovt.", translation: "Teknemle oynuyorum.", color: "lightblue" },
        { word: "Plane", sentence: "I'm playing with my plane.", pronunciation: "Aym pleying vit may pleyn.", translation: "Uçağımla oynuyorum.", color: "lightgray" },
        { word: "Lego", sentence: "I build with lego.", pronunciation: "Ay bild vit lego.", translation: "Lego ile inşa ederim.", color: "lightcoral" },
        { word: "Puzzle", sentence: "The puzzle is fun.", pronunciation: "Dı pazıl iz fan.", translation: "Yapboz eğlenceli.", color: "lightyellow" },
        { word: "Car", sentence: "This is a toy car.", pronunciation: "Dis iz e toy kar.", translation: "Bu bir oyuncak araba.", color: "lightgreen" },
        { word: "Train", sentence: "The train goes choo-choo.", pronunciation: "Dı treyn goz çu-çu.", translation: "Tren çuf çuf gider.", color: "lightcyan" },
        { word: "Doll", sentence: "She loves her doll.", pronunciation: "Şi lavz her dol.", translation: "Bebeğini seviyor.", color: "lightpink" },
        { word: "Robot", sentence: "The robot can dance.", pronunciation: "Dı robot ken dans.", translation: "Robot dans edebilir.", color: "lavender" },
        { word: "Ball", sentence: "I have a ball.", pronunciation: "Ay hev e bol.", translation: "Bir topum var.", color: "peachpuff" },
        { word: "Kite", sentence: "The kite flies high.", pronunciation: "Dı kayt flayz hay.", translation: "Uçurtma yüksekte uçar.", color: "lightsteelblue" },
        { word: "Present", sentence: "I have a present for you.", pronunciation: "Ay hev e prezant for yu.", translation: "Senin için bir hediyem var.", color: "plum" }
    ],
    "Clothes": [
        { word: "T-shirt", sentence: "This is a blue T-shirt.", pronunciation: "Dis iz e blu tii-şört.", translation: "Bu mavi bir tişört.", color: "lightblue" },
        { word: "Shorts", sentence: "This is yellow short.", pronunciation: "Dis iz yelov şort.", translation: "Bu sarı bir şort.", color: "lightcyan" },
        { word: "Coat", sentence: "I wear a coat in winter.", pronunciation: "Ay veer e kovt in vintır.", translation: "Kışın palto giyerim.", color: "lightgray" },
        { word: "Boots", sentence: "In winter, we wear boots.", pronunciation: "İn vintır, vi veer buts.", translation: "Kışın bot giyeriz.", color: "tan" },
        { word: "Hat", sentence: "Put on the hat!", pronunciation: "Put on dı het!", translation: "Şapkayı giy!", color: "lightyellow" },
        { word: "Shoes", sentence: "My shoes are brown.", pronunciation: "May şuuz ar bravn.", translation: "Ayakkabılarım kahverengi.", color: "lightcoral" },
        { word: "Dress", sentence: "This is a green dress.", pronunciation: "Dis iz e griin dres.", translation: "Bu yeşil bir elbise.", color: "lightpink" },
        { word: "Skirt", sentence: "This is a green skirt.", pronunciation: "Dis iz e griin skört.", translation: "Bu yeşil bir etek.", color: "plum" },
        { word: "Pants", sentence: "This is a blue pants.", pronunciation: "Dis iz e blu pents.", translation: "Bu mavi bir pantolon.", color: "lightgreen" },
        { word: "Socks", sentence: "I'm wearing brown socks.", pronunciation: "Aym veering bravn saks.", translation: "Kahverengi çoraplar giyiyorum.", color: "lightcoral" },
        { word: "Scarf", sentence: "In winter, we wear scarves.", pronunciation: "İn vintır, vi veer skarvz.", translation: "Kışın atkı giyeriz.", color: "plum" },
        { word: "Gloves", sentence: "Put on your gloves!", pronunciation: "Put on yor glavz!", translation: "Eldivenlerini giy!", color: "lightblue" },
        { word: "Sweater", sentence: "I'm wearing a sweater.", pronunciation: "Aym veering e suetır.", translation: "Kazak giyiyorum.", color: "lightcoral" },
        { word: "Umbrella", sentence: "Take your umbrella.", pronunciation: "Teyk yor ambrella.", translation: "Şemsiyeni al.", color: "lightsteelblue" },
        { word: "Raincoat", sentence: "Wear your raincoat.", pronunciation: "Veer yor reynkovt.", translation: "Yağmurluğunu giy.", color: "lightyellow" },
        { word: "Rainboots", sentence: "These are rainboots.", pronunciation: "Diiz ar reynbuts.", translation: "Bunlar yağmur çizmeleri.", color: "lightgreen" },
        { word: "Sunglasses", sentence: "Put on your sunglasses.", pronunciation: "Put on yor sangılasız.", translation: "Güneş gözlüklerini tak.", color: "lavender" },
        { word: "Slippers", sentence: "This is a slippers.", pronunciation: "Dis iz e slipırz.", translation: "Bu terlik.", color: "peachpuff" }
    ],
    "Body Parts": [
        { word: "Head", sentence: "Touch your head.", pronunciation: "Taç yor hed.", translation: "Başına dokun.", color: "peachpuff" },
        { word: "Eye", sentence: "I have two eyes.", pronunciation: "Ay hev tu ayz.", translation: "İki gözüm var.", color: "lightblue" },
        { word: "Nose", sentence: "This is a nose.", pronunciation: "Dis iz e novz.", translation: "Bu bir burun.", color: "lightpink" },
        { word: "Mouth", sentence: "I eat with my mouth.", pronunciation: "Ay iit vit may mavt.", translation: "Ağzımla yerim.", color: "lightcoral" },
        { word: "Ear", sentence: "I hear with my ears.", pronunciation: "Ay hiir vit may iirz.", translation: "Kulaklarımla duyarım.", color: "lightyellow" },
        { word: "Arm", sentence: "I have two arms.", pronunciation: "Ay hev tu armz.", translation: "İki kolum var.", color: "lightgreen" },
        { word: "Leg", sentence: "My legs are long.", pronunciation: "May legz ar long.", translation: "Bacaklarım uzun.", color: "lightcyan" },
        { word: "Hand", sentence: "I write with my hand.", pronunciation: "Ay rayt vit may hend.", translation: "Elimle yazarım.", color: "lavender" },
        { word: "Foot", sentence: "I walk with my feet.", pronunciation: "Ay vok vit may fiit.", translation: "Ayaklarımla yürürüm.", color: "tan" },
        { word: "Tongue", sentence: "The monster has a big tongue.", pronunciation: "Dı monstır hez e big tang.", translation: "Canavarın büyük bir dili var.", color: "lightcoral" }
    ],
    "Shapes": [
        { word: "Circle", sentence: "This is a circle.", pronunciation: "Dis iz e sörkıl.", translation: "Bu bir daire.", color: "lightcyan" },
        { word: "Triangle", sentence: "Hop on the triangle.", pronunciation: "Hop on dı trayangıl.", translation: "Üçgenin üzerine zıpla.", color: "lightcoral" },
        { word: "Square", sentence: "This is a square.", pronunciation: "Dis iz e skueır.", translation: "Bu bir kare.", color: "lightyellow" },
        { word: "Rectangle", sentence: "This is a rectangle.", pronunciation: "Dis iz e rektengıl.", translation: "Bu bir dikdörtgen.", color: "lightgreen" },
        { word: "Heart", sentence: "This is a pink heart.", pronunciation: "Dis iz e pink hart.", translation: "Bu pembe bir kalp.", color: "lightpink" }
    ],
    "Weather & Seasons": [
        { word: "Sunny", sentence: "It's sunny in summer.", pronunciation: "İts sani in samır.", translation: "Yazın hava güneşli.", color: "lightyellow" },
        { word: "Rainy", sentence: "It's rainy in spring.", pronunciation: "İts reyni in spring.", translation: "İlkbaharda yağmurlu.", color: "lightblue" },
        { word: "Snowy", sentence: "It's snowy in winter.", pronunciation: "İts snovi in vintır.", translation: "Kışın karlı.", color: "white" },
        { word: "Windy", sentence: "It's windy today.", pronunciation: "İts vindi tudey.", translation: "Bugün rüzgarlı.", color: "lightgray" },
        { word: "Hot", sentence: "Summer is hot.", pronunciation: "Samır iz hat.", translation: "Yaz sıcaktır.", color: "lightcoral" },
        { word: "Cold", sentence: "Winter is cold.", pronunciation: "Vintır iz kold.", translation: "Kış soğuktur.", color: "lightcyan" },
        { word: "Spring", sentence: "Flowers bloom in spring.", pronunciation: "Flavvırz blum in spring.", translation: "İlkbaharda çiçekler açar.", color: "lightgreen" },
        { word: "Summer", sentence: "We swim in summer.", pronunciation: "Vi suim in samır.", translation: "Yazın yüzeriz.", color: "lightyellow" },
        { word: "Fall", sentence: "Leaves fall in fall.", pronunciation: "Liivz fol in fol.", translation: "Sonbaharda yapraklar düşer.", color: "peachpuff" },
        { word: "Winter", sentence: "We wear coats in winter.", pronunciation: "Vi veer kovts in vintır.", translation: "Kışın palto giyeriz.", color: "lightblue" },
        { word: "Buoyancy", sentence: "How the ship sail? Learning the buoyancy of water.", pronunciation: "Hav dı şip seyl? Lörning dı boyınsi ov votır.", translation: "Gemi nasıl yüzer? Suyun kaldırma kuvvetini öğreniyoruz.", color: "lightblue" }
    ],
    "Classroom Objects": [
        { word: "Book", sentence: "This is a book.", pronunciation: "Dis iz e buk.", translation: "Bu bir kitap.", color: "lightblue" },
        { word: "Pencil", sentence: "It's a pencil.", pronunciation: "İts e pensıl.", translation: "Bu bir kalem.", color: "lightgray" },
        { word: "Chair", sentence: "It's a chair.", pronunciation: "İts e çeir.", translation: "Bu bir sandalye.", color: "tan" },
        { word: "Table", sentence: "This is a table.", pronunciation: "Dis iz e teybıl.", translation: "Bu bir masa.", color: "lightgreen" },
        { word: "Crayon", sentence: "What's this? This is a crayon.", pronunciation: "Vats dis? Dis iz e kreyyon.", translation: "Bu ne? Bu bir pastel boya.", color: "lightpink" },
        { word: "Glue", sentence: "I want the glue, please!", pronunciation: "Ay vont dı glu, pliiz!", translation: "Yapıştırıcıyı istiyorum, lütfen!", color: "lightyellow" },
        { word: "Schoolbag", sentence: "This is my schoolbag.", pronunciation: "Dis iz may skulbeg.", translation: "Bu benim okul çantam.", color: "lightcyan" },
        { word: "Scissors", sentence: "Here are the scissors.", pronunciation: "Hiir ar dı sizırz.", translation: "İşte makas.", color: "lightcoral" },
        { word: "Sharpener", sentence: "What's this? It's a sharpener.", pronunciation: "Vats dis? İts e şarpınır.", translation: "Bu ne? Bu bir kalemtraş.", color: "lavender" },
        { word: "Eraser", sentence: "I want the eraser, please!", pronunciation: "Ay vont dı ireyzır, pliiz!", translation: "Silgiyi istiyorum, lütfen!", color: "peachpuff" },
        { word: "Window", sentence: "It's a window.", pronunciation: "İts e vindov.", translation: "Bu bir pencere.", color: "lightsteelblue" },
        { word: "Door", sentence: "It's a door.", pronunciation: "İts e dor.", translation: "Bu bir kapı.", color: "plum" },
        { word: "Ruler", sentence: "Where is my ruler?", pronunciation: "Veır iz may rulır?", translation: "Cetvelim nerede?", color: "lightgray" },
        { word: "Notebook", sentence: "This is my notebook.", pronunciation: "Dis iz may novtbuk.", translation: "Bu benim defterim.", color: "white" }
    ],
    "Feelings & Emotions": [
        { word: "Happy", sentence: "I am happy.", pronunciation: "Ay em heppi.", translation: "Ben mutluyum.", color: "lightyellow" },
        { word: "Angry", sentence: "I am angry.", pronunciation: "Ay em engri.", translation: "Ben kızgınım.", color: "lightcoral" },
        { word: "Surprised", sentence: "I am surprised.", pronunciation: "Ay em sırprayzd.", translation: "Şaşırdım.", color: "lightpink" },
        { word: "Sad", sentence: "I am sad.", pronunciation: "Ay em sed.", translation: "Üzgünüm.", color: "lightblue" },
        { word: "Sleepy", sentence: "I am sleepy.", pronunciation: "Ay em slipi.", translation: "Uykum var.", color: "lavender" },
        { word: "Hungry", sentence: "I'm hungry. I want some fish.", pronunciation: "Aym hangri. Ay vont sam fiş.", translation: "Açım. Biraz balık istiyorum.", color: "peachpuff" },
        { word: "Thirsty", sentence: "I'm thirsty. I want some milk.", pronunciation: "Aym tırsti. Ay vont sam milk.", translation: "Susadım. Biraz süt istiyorum.", color: "lightcyan" }
    ],
    "House & Furniture": [
        { word: "House", sentence: "This is my house.", pronunciation: "Dis iz may havs.", translation: "Bu benim evim.", color: "lightblue" },
        { word: "Living Room", sentence: "This is the living room.", pronunciation: "Dis iz dı living rum.", translation: "Bu oturma odası.", color: "lightpink" },
        { word: "Bedroom", sentence: "I'm in the bedroom.", pronunciation: "Aym in dı bedrum.", translation: "Yatak odasındayım.", color: "lightyellow" },
        { word: "Bathroom", sentence: "Where is mom? Mom is in the bathroom.", pronunciation: "Veır iz mom? Mom iz in dı batrum.", translation: "Anne nerede? Anne banyoda.", color: "lightgreen" },
        { word: "Kitchen", sentence: "Dad is in the kitchen cooking.", pronunciation: "Ded iz in dı kiçın kuking.", translation: "Babam mutfakta yemek yapıyor.", color: "lightcyan" },
        { word: "Sofa", sentence: "This is a sofa.", pronunciation: "Dis iz e sofa.", translation: "Bu bir kanepe.", color: "lavender" },
        { word: "Bed", sentence: "Sleep in bed.", pronunciation: "Sliip in bed.", translation: "Yatakta uyu.", color: "peachpuff" },
        { word: "Fridge", sentence: "This is a fridge.", pronunciation: "Dis iz e friç.", translation: "Bu bir buzdolabı.", color: "lightsteelblue" },
        { word: "Television", sentence: "The television is in the living room.", pronunciation: "Dı televizyın iz in dı living rum.", translation: "Televizyon oturma odasında.", color: "plum" },
        { word: "Table", sentence: "The table is in the kitchen.", pronunciation: "Dı teybıl iz in dı kiçın.", translation: "Masa mutfakta.", color: "tan" }
    ],
    "Playground": [
        { word: "Slide", sentence: "I can slide.", pronunciation: "Ay ken slayd.", translation: "Kayabilirim.", color: "lightblue" },
        { word: "Swing", sentence: "I'm swinging.", pronunciation: "Aym suinging.", translation: "Sallanıyorum.", color: "lightpink" },
        { word: "See-saw", sentence: "This is a see-saw.", pronunciation: "Dis iz e sii-soo.", translation: "Bu bir tahterevalli.", color: "lightyellow" },
        { word: "Sandbox", sentence: "Let's play in the sandbox.", pronunciation: "Lets pley in dı sendbaks.", translation: "Kum havuzunda oynayalım.", color: "tan" },
        { word: "Map", sentence: "Look at the map.", pronunciation: "Luk et dı mep.", translation: "Haritaya bak.", color: "lightgreen" },
        { word: "Bottle", sentence: "I have a water bottle.", pronunciation: "Ay hev e votır batıl.", translation: "Bir su şişem var.", color: "lightcyan" }
    ],
    "Days": [
        { word: "Monday", sentence: "What day is it today? It's Monday.", pronunciation: "Vat dey iz it tudey? İts Mandey.", translation: "Bugün günlerden ne? Pazartesi.", color: "lightblue" },
        { word: "Tuesday", sentence: "What day is it today? It's Tuesday.", pronunciation: "Vat dey iz it tudey? İts Tuzdey.", translation: "Bugün günlerden ne? Salı.", color: "lightpink" },
        { word: "Wednesday", sentence: "What day is it today? It's Wednesday.", pronunciation: "Vat dey iz it tudey? İts Venzdey.", translation: "Bugün günlerden ne? Çarşamba.", color: "lightyellow" },
        { word: "Thursday", sentence: "What day is it today? It's Thursday.", pronunciation: "Vat dey iz it tudey? İts Tırzdey.", translation: "Bugün günlerden ne? Perşembe.", color: "lightgreen" },
        { word: "Friday", sentence: "What day is it today? It's Friday.", pronunciation: "Vat dey iz it tudey? İts Fraydey.", translation: "Bugün günlerden ne? Cuma.", color: "lightcyan" },
        { word: "Saturday", sentence: "What day is it today? It's Saturday.", pronunciation: "Vat dey iz it tudey? İts Setırdey.", translation: "Bugün günlerden ne? Cumartesi.", color: "lavender" },
        { word: "Sunday", sentence: "What day is it today? It's Sunday.", pronunciation: "Vat dey iz it tudey? İts Sandey.", translation: "Bugün günlerden ne? Pazar.", color: "peachpuff" }
    ],
    "Classroom Rules": [
        { word: "Sit down", sentence: "Sit down, please.", pronunciation: "Sit davn, pliiz.", translation: "Lütfen otur.", color: "lightblue" },
        { word: "Stand up", sentence: "Stand up, please.", pronunciation: "Stend ap, pliiz.", translation: "Lütfen ayağa kalk.", color: "lightpink" },
        { word: "Listen", sentence: "Listen to the teacher.", pronunciation: "Lisın tu dı tiiçır.", translation: "Öğretmeni dinle.", color: "lightyellow" },
        { word: "Don't run", sentence: "Don't run in the classroom.", pronunciation: "Dont ran in dı klasrum.", translation: "Sınıfta koşma.", color: "lightgreen" },
        { word: "Turn off/on", sentence: "Turn off/on the light.", pronunciation: "Tırn of/on dı layt.", translation: "Işığı kapat/aç.", color: "lightcyan" },
        { word: "Look at", sentence: "Look at the smartboard.", pronunciation: "Luk et dı smartbord.", translation: "Akıllı tahtaya bak.", color: "lavender" }
    ],
    "Greetings & Basics": [
        { word: "What's your name?", sentence: "What's your name? I'm Evren.", pronunciation: "Vats yor neym? Aym Evren.", translation: "Adın ne? Ben Evren.", color: "lightblue" },
        { word: "I'm (name)", sentence: "I'm Nehir. Nice to meet you.", pronunciation: "Aym Nehir. Nays tu miit yu.", translation: "Ben Nehir. Tanıştığıma memnun oldum.", color: "lightpink" },
        { word: "My school", sentence: "This is my school.", pronunciation: "Dis iz may skul.", translation: "Bu benim okulum.", color: "lightyellow" },
        { word: "My friends", sentence: "These are my friends.", pronunciation: "Diiz ar may frends.", translation: "Bunlar benim arkadaşlarım.", color: "lightgreen" },
        { word: "My teacher", sentence: "This is my teacher.", pronunciation: "Dis iz may tiiçır.", translation: "Bu benim öğretmenim.", color: "lightcyan" },
        { word: "Hello", sentence: "Hello, how are you?", pronunciation: "Hello, hav ar yu?", translation: "Merhaba, nasılsın?", color: "lavender" },
        { word: "Goodbye", sentence: "Goodbye, see you tomorrow.", pronunciation: "Gudbay, sii yu tumarov.", translation: "Hoşça kal, yarın görüşürüz.", color: "peachpuff" }
    ],
    "Polite Requests": [
        { word: "Thank you", sentence: "Thank you! You're welcome.", pronunciation: "Tenk yu! Yor velkım.", translation: "Teşekkür ederim! Rica ederim.", color: "lightpink" },
        { word: "Please", sentence: "I want the book, please!", pronunciation: "Ay vont dı buk, pliiz!", translation: "Kitabı istiyorum, lütfen!", color: "lightblue" },
        { word: "You're welcome", sentence: "Thank you! You're welcome.", pronunciation: "Tenk yu! Yor velkım.", translation: "Teşekkür ederim! Rica ederim.", color: "lightyellow" },
        { word: "Here you are", sentence: "Can I have the pencil? Here you are.", pronunciation: "Ken ay hev dı pensıl? Hiir yu ar.", translation: "Kalemi alabilir miyim? Buyurun.", color: "lightgreen" },
        { word: "Excuse me", sentence: "Excuse me, teacher.", pronunciation: "Ekskyúz mi, tiiçır.", translation: "Affedersiniz, öğretmenim.", color: "lightcyan" }
    ],
    "Daily Actions": [
        { word: 'Eat', sentence: 'I eat breakfast.', pronunciation: 'Ay iit brekfıst.', translation: 'Kahvaltı yapıyorum.', color: 'lightsalmon' },
        { word: 'Sleep', sentence: 'I sleep at night.', pronunciation: 'Ay sliip et nayt.', translation: 'Geceleri uyurum.', color: 'lightgray' },
        { word: 'Run', sentence: 'I run in the park.', pronunciation: 'Ay ran in dı park.', translation: 'Parkta koşarım.', color: 'lightgreen' },
        { word: 'Walk', sentence: 'I walk to school.', pronunciation: 'Ay vok tu skul.', translation: 'Okula yürüyerek giderim.', color: 'tan' },
        { word: 'Jump', sentence: 'Children jump for joy.', pronunciation: 'Çildrın camp for coy.', translation: 'Çocuklar sevinçten zıplar.', color: 'lightcoral' },
        { word: 'Read', sentence: 'I read a book.', pronunciation: 'Ay riid e buk.', translation: 'Kitap okurum.', color: 'lightpink' },
        { word: 'Write', sentence: 'I write with a pencil.', pronunciation: 'Ay rayt vit e pensıl.', translation: 'Kalemle yazarım.', color: 'lightblue' },
        { word: 'Sing', sentence: 'She sings a song.', pronunciation: 'şi sings e song.', translation: 'O bir şarkı söylüyor.', color: 'plum' },
        { word: 'Dance', sentence: 'We dance at the party.', pronunciation: 'Vi dans et dı parti.', translation: 'Partide dans ederiz.', color: 'lightcyan' },
        { word: 'Play', sentence: 'Children play games.', pronunciation: 'Çildrın pley geyms.', translation: 'Çocuklar oyun oynar.', color: 'lightyellow' },
        { word: 'Tidy up', sentence: 'Tidy up your toys!', pronunciation: 'Taydi ap yor toys!', translation: 'Oyuncaklarını topla!', color: 'lightyellow' },
        { word: 'Dig', sentence: 'Let\'s dig for fossils!', pronunciation: 'Lets dig for fasılz!', translation: 'Hadi fosil kazalım!', color: 'tan' },
        { word: 'Bounce', sentence: 'The ball is bouncing.', pronunciation: 'Dı bol iz bavnsing.', translation: 'Top zıplıyor.', color: 'lightcoral' },
        { word: 'Row', sentence: 'The boat is rowing.', pronunciation: 'Dı bovt iz roving.', translation: 'Tekne kürek çekiyor.', color: 'lightblue' }
    ],
    'Science': [
        { word: 'Fossil', sentence: 'We found a fossil!', pronunciation: 'Vi favnd e fasıl!', translation: 'Bir fosil bulduk!', color: 'tan' },
        { word: 'Archeology', sentence: 'We learn about archeology.', pronunciation: 'Vi lörn ebavt arkioloci.', translation: 'Arkeoloji hakkında bilgi ediniyoruz.', color: 'peachpuff' },
        { word: 'Pickaxe', sentence: 'Use the pickaxe carefully.', pronunciation: 'Yuz dı pikeks kerfuli.', translation: 'Kazmayı dikkatli kullan.', color: 'lightgray' },
        { word: 'Volcano', sentence: 'The volcano is erupting!', pronunciation: 'Dı volkeyno iz iraptin!', translation: 'Volkan patlıyor!', color: 'lightcoral' },
        { word: 'Eruption', sentence: 'Look at the eruption!', pronunciation: 'Luk et dı irapşın!', translation: 'Patlamaya bak!', color: 'sienna' },
        { word: 'Rainbow', sentence: 'Let\'s create a rainbow!', pronunciation: 'Lets kriyet e reynbov!', translation: 'Hadi gökkuşağı yapalım!', color: 'violet' },
        { word: 'Seed', sentence: 'Plant the seed.', pronunciation: 'Plent dı siid.', translation: 'Tohumu ek.', color: 'tan' },
        { word: 'Soil', sentence: 'Farming without soil.', pronunciation: 'Farmin vitvavt soyl.', translation: 'Topraksız tarım.', color: 'sienna' }
    ]
};

// Dışa aktarma
module.exports = {
    themes
};